//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexxtDent.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software para el control y administracion de Laboratorios Dentales InfoDent.  De la misma casa de Infoplanet-Team..
        /// </summary>
        public static string About_Information {
            get {
                return ResourceManager.GetString("About_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Acceso.
        /// </summary>
        public static string Account_Login_Logueo {
            get {
                return ResourceManager.GetString("Account_Login_Logueo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Trabajos.
        /// </summary>
        public static string AsignarTrabajo {
            get {
                return ResourceManager.GetString("AsignarTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string ButtonActivar {
            get {
                return ResourceManager.GetString("ButtonActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular.
        /// </summary>
        public static string ButtonAnular {
            get {
                return ResourceManager.GetString("ButtonAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ButtonDetail {
            get {
                return ResourceManager.GetString("ButtonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string ButtonFactura {
            get {
                return ResourceManager.GetString("ButtonFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string ButtonPagos {
            get {
                return ResourceManager.GetString("ButtonPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnicos.
        /// </summary>
        public static string ButtonTechnical {
            get {
                return ResourceManager.GetString("ButtonTechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Venta.
        /// </summary>
        public static string ButtonTiketVenta {
            get {
                return ResourceManager.GetString("ButtonTiketVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        public static string ButtonWork {
            get {
                return ResourceManager.GetString("ButtonWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_Model_City {
            get {
                return ResourceManager.GetString("City_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("City_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Client_Model_Address {
            get {
                return ResourceManager.GetString("Client_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        public static string Client_Model_Cell {
            get {
                return ResourceManager.GetString("Client_Model_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinica.
        /// </summary>
        public static string Client_Model_Client {
            get {
                return ResourceManager.GetString("Client_Model_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Client_Model_Date {
            get {
                return ResourceManager.GetString("Client_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Documento.
        /// </summary>
        public static string Client_Model_DocumentNumber {
            get {
                return ResourceManager.GetString("Client_Model_DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Client_Model_DocumentType {
            get {
                return ResourceManager.GetString("Client_Model_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Client_Model_Phone {
            get {
                return ResourceManager.GetString("Client_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinica.
        /// </summary>
        public static string Client_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Client_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccionar...].
        /// </summary>
        public static string ComboSelect {
            get {
                return ResourceManager.GetString("ComboSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Company_Model_Active {
            get {
                return ResourceManager.GetString("Company_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Company_Model_Address {
            get {
                return ResourceManager.GetString("Company_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string Company_Model_Anulado {
            get {
                return ResourceManager.GetString("Company_Model_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_Model_Compania {
            get {
                return ResourceManager.GetString("Company_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Company_Model_Country {
            get {
                return ResourceManager.GetString("Company_Model_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Company_Model_Desde {
            get {
                return ResourceManager.GetString("Company_Model_Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Company_Model_Hasta {
            get {
                return ResourceManager.GetString("Company_Model_Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Company_Model_Logo {
            get {
                return ResourceManager.GetString("Company_Model_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Company_Model_Phone {
            get {
                return ResourceManager.GetString("Company_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit / CI.
        /// </summary>
        public static string Company_Model_Rif {
            get {
                return ResourceManager.GetString("Company_Model_Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Company_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono.
        /// </summary>
        public static string CxC_Model_Abono {
            get {
                return ResourceManager.GetString("CxC_Model_Abono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string CxC_Model_Anulado {
            get {
                return ResourceManager.GetString("CxC_Model_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Pagado.
        /// </summary>
        public static string CxC_Model_FechaPagado {
            get {
                return ResourceManager.GetString("CxC_Model_FechaPagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagado.
        /// </summary>
        public static string CxC_Model_Pagado {
            get {
                return ResourceManager.GetString("CxC_Model_Pagado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Cxc_Model_Saldo {
            get {
                return ResourceManager.GetString("Cxc_Model_Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string CxC_Model_Total {
            get {
                return ResourceManager.GetString("CxC_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Cuentas por Pagar.
        /// </summary>
        public static string CxC_Reporte {
            get {
                return ResourceManager.GetString("CxC_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular Cuenta por Cobrar.
        /// </summary>
        public static string CxC_View_IndexTitulo {
            get {
                return ResourceManager.GetString("CxC_View_IndexTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        public static string CxC_View_Payments {
            get {
                return ResourceManager.GetString("CxC_View_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por Cobrar.
        /// </summary>
        public static string CxC_ViewIndex_CuentasXcobrar {
            get {
                return ResourceManager.GetString("CxC_ViewIndex_CuentasXcobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturado.
        /// </summary>
        public static string CxCBillDetail_Model_Facturado {
            get {
                return ResourceManager.GetString("CxCBillDetail_Model_Facturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string CxCCanceled_Model_Motivo {
            get {
                return ResourceManager.GetString("CxCCanceled_Model_Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega.
        /// </summary>
        public static string Delivery_Button_AddDelivery {
            get {
                return ResourceManager.GetString("Delivery_Button_AddDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despachos.
        /// </summary>
        public static string Delivery_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Delivery_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregado Por.
        /// </summary>
        public static string DeliveryDetail_Model_Delivered {
            get {
                return ResourceManager.GetString("DeliveryDetail_Model_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string DeliveryDetail_Model_Detalle {
            get {
                return ResourceManager.GetString("DeliveryDetail_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibido Por.
        /// </summary>
        public static string DeliveryDetail_Model_Received {
            get {
                return ResourceManager.GetString("DeliveryDetail_Model_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        public static string FechaDesde {
            get {
                return ResourceManager.GetString("FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        public static string FechaHasta {
            get {
                return ResourceManager.GetString("FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string GumColor_Model_Detalle {
            get {
                return ResourceManager.GetString("GumColor_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Encia.
        /// </summary>
        public static string GumColor_Model_GumColor {
            get {
                return ResourceManager.GetString("GumColor_Model_GumColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Encia.
        /// </summary>
        public static string GumColor_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("GumColor_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lleve el control de las cuentas por cobrar de sus clientes, puede controlar los abonos por cada trabajo despachado..
        /// </summary>
        public static string Home_IndexText_Cobros {
            get {
                return ResourceManager.GetString("Home_IndexText_Cobros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realice el pago o abonos de los trabajos realizados a sus tecnicos. Controle todos los egresos del laboratorios..
        /// </summary>
        public static string Home_IndexText_Pagos {
            get {
                return ResourceManager.GetString("Home_IndexText_Pagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibe los trabajos de sus clientes y asigne los tecnicos necesarios, supervise el estado y los despachos..
        /// </summary>
        public static string Home_IndexTexto_Trabajos {
            get {
                return ResourceManager.GetString("Home_IndexTexto_Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Egresos.
        /// </summary>
        public static string Home_IndexTitulo_PagosEgresos {
            get {
                return ResourceManager.GetString("Home_IndexTitulo_PagosEgresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        public static string Home_IndexTitulo_Trabajos {
            get {
                return ResourceManager.GetString("Home_IndexTitulo_Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por Cobrar.
        /// </summary>
        public static string Homo_IndexTitulo_CuentasCobrar {
            get {
                return ResourceManager.GetString("Homo_IndexTitulo_CuentasCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Identification_Model_TipoDocumento {
            get {
                return ResourceManager.GetString("Identification_Model_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Identification_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Identification_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotaCobro/Factura.
        /// </summary>
        public static string Income_BillingNoteControl {
            get {
                return ResourceManager.GetString("Income_BillingNoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos Diarios.
        /// </summary>
        public static string Income_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Income_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Income_Model_Control {
            get {
                return ResourceManager.GetString("Income_Model_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string Income_Model_Monto {
            get {
                return ResourceManager.GetString("Income_Model_Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        public static string Income_Model_Origen {
            get {
                return ResourceManager.GetString("Income_Model_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_Model_PriceLevel {
            get {
                return ResourceManager.GetString("LevelPrice_Model_PriceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("LevelPrice_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} debe ser menor de {1} characters.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Menu_Ingresar {
            get {
                return ResourceManager.GetString("Menu_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Menu_Salir {
            get {
                return ResourceManager.GetString("Menu_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosotros.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrativo.
        /// </summary>
        public static string MenuAdmin_Admin {
            get {
                return ResourceManager.GetString("MenuAdmin_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas por Cobrar.
        /// </summary>
        public static string MenuAdmin_CuentasxCobrar {
            get {
                return ResourceManager.GetString("MenuAdmin_CuentasxCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta por Cobrar Anuladas.
        /// </summary>
        public static string MenuAdmin_CuentasxCobrarAnulado {
            get {
                return ResourceManager.GetString("MenuAdmin_CuentasxCobrarAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante Egresos.
        /// </summary>
        public static string MenuAdmin_Egresos {
            get {
                return ResourceManager.GetString("MenuAdmin_Egresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresos Diarios.
        /// </summary>
        public static string MenuAdmin_Ingresos {
            get {
                return ResourceManager.GetString("MenuAdmin_Ingresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidar Tecnicos.
        /// </summary>
        public static string MenuAdmin_PagoTecnicos {
            get {
                return ResourceManager.GetString("MenuAdmin_PagoTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string MenuArchivo_Archivo {
            get {
                return ResourceManager.GetString("MenuArchivo_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Servicio.
        /// </summary>
        public static string MenuArchivo_CategoriaServicio {
            get {
                return ResourceManager.GetString("MenuArchivo_CategoriaServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Trabajos.
        /// </summary>
        public static string MenuArchivo_CategoriaTrabajos {
            get {
                return ResourceManager.GetString("MenuArchivo_CategoriaTrabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string MenuArchivo_Ciudad {
            get {
                return ResourceManager.GetString("MenuArchivo_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinicas.
        /// </summary>
        public static string MenuArchivo_Clinicas {
            get {
                return ResourceManager.GetString("MenuArchivo_Clinicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion Trabajo.
        /// </summary>
        public static string MenuArchivo_EstacionTrabajo {
            get {
                return ResourceManager.GetString("MenuArchivo_EstacionTrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string MenuArchivo_Servicio {
            get {
                return ResourceManager.GetString("MenuArchivo_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnicos.
        /// </summary>
        public static string MenuArchivo_Tecnicos {
            get {
                return ResourceManager.GetString("MenuArchivo_Tecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos.
        /// </summary>
        public static string MenuArchivo_Trabajos {
            get {
                return ResourceManager.GetString("MenuArchivo_Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string MenuArchivo_Zona {
            get {
                return ResourceManager.GetString("MenuArchivo_Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones.
        /// </summary>
        public static string MenuOperacion_Operations {
            get {
                return ResourceManager.GetString("MenuOperacion_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Tecnicos.
        /// </summary>
        public static string MenuOperation_Asignar {
            get {
                return ResourceManager.GetString("MenuOperation_Asignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despacho Trabajos.
        /// </summary>
        public static string MenuOperation_Despachos {
            get {
                return ResourceManager.GetString("MenuOperation_Despachos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string MenuOperation_Recepcion {
            get {
                return ResourceManager.GetString("MenuOperation_Recepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo Tecnicos.
        /// </summary>
        public static string MenuOpration_Trabajos {
            get {
                return ResourceManager.GetString("MenuOpration_Trabajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Diente.
        /// </summary>
        public static string MenuSystem_ColorDiente {
            get {
                return ResourceManager.GetString("MenuSystem_ColorDiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Encia.
        /// </summary>
        public static string MenuSystem_ColorEncia {
            get {
                return ResourceManager.GetString("MenuSystem_ColorEncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string MenuSystem_Consecutivo {
            get {
                return ResourceManager.GetString("MenuSystem_Consecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string MenuSystem_DocumentType {
            get {
                return ResourceManager.GetString("MenuSystem_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string MenuSystem_Impuesto {
            get {
                return ResourceManager.GetString("MenuSystem_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string MenuSystem_System {
            get {
                return ResourceManager.GetString("MenuSystem_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje Tecnicos.
        /// </summary>
        public static string MenuSystem_TechicalPorcentaje {
            get {
                return ResourceManager.GetString("MenuSystem_TechicalPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string MenuSystem_TextoEncabezado {
            get {
                return ResourceManager.GetString("MenuSystem_TextoEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        public static string ModoPago_Cheque {
            get {
                return ResourceManager.GetString("ModoPago_Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efectivo.
        /// </summary>
        public static string ModoPago_Efectivo {
            get {
                return ResourceManager.GetString("ModoPago_Efectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencia.
        /// </summary>
        public static string ModoPago_Transferencia {
            get {
                return ResourceManager.GetString("ModoPago_Transferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un Registro con el mismo Valor.
        /// </summary>
        public static string Msg_DoubleData {
            get {
                return ResourceManager.GetString("Msg_DoubleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar un Item.
        /// </summary>
        public static string Msg_Range {
            get {
                return ResourceManager.GetString("Msg_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registo no puede ser Eliminado, porque tiene relacion con otros Datos.
        /// </summary>
        public static string Msg_Relationship {
            get {
                return ResourceManager.GetString("Msg_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El pago debe ser Mayor a Cero.
        /// </summary>
        public static string Msg_SaldoMayorCero {
            get {
                return ResourceManager.GetString("Msg_SaldoMayorCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnico Cobra Procentaje, los Precios deben ser Mayor a Cero.
        /// </summary>
        public static string Msg_TecnicoPorcentaje {
            get {
                return ResourceManager.GetString("Msg_TecnicoPorcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Activar ya la Recepcion?.
        /// </summary>
        public static string MsgActivar {
            get {
                return ResourceManager.GetString("MsgActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Eliminar este Registro?.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratorio Dental.
        /// </summary>
        public static string NombreSoftware {
            get {
                return ResourceManager.GetString("NombreSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string Outcome_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Outcome_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Egresos.
        /// </summary>
        public static string Outcome_IndexView_Titulo12 {
            get {
                return ResourceManager.GetString("Outcome_IndexView_Titulo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario.
        /// </summary>
        public static string Outcome_Model_Beneficiario {
            get {
                return ResourceManager.GetString("Outcome_Model_Beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Outcome_Model_Date {
            get {
                return ResourceManager.GetString("Outcome_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Outcome_Model_Detalle {
            get {
                return ResourceManager.GetString("Outcome_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egreso.
        /// </summary>
        public static string Outcome_Model_Egreso {
            get {
                return ResourceManager.GetString("Outcome_Model_Egreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Egreso.
        /// </summary>
        public static string Outcome_Model_TotalValue {
            get {
                return ResourceManager.GetString("Outcome_Model_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string OutcomeDetail_Model_Document {
            get {
                return ResourceManager.GetString("OutcomeDetail_Model_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string OutcomeDetail_Model_Valor {
            get {
                return ResourceManager.GetString("OutcomeDetail_Model_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinica.
        /// </summary>
        public static string Reception_Model_Clinic {
            get {
                return ResourceManager.GetString("Reception_Model_Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Reception_Model_Date {
            get {
                return ResourceManager.GetString("Reception_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Entrega.
        /// </summary>
        public static string Reception_Model_DeliverDate {
            get {
                return ResourceManager.GetString("Reception_Model_DeliverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Reception_Model_Detail {
            get {
                return ResourceManager.GetString("Reception_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Encia.
        /// </summary>
        public static string Reception_Model_GumColor {
            get {
                return ResourceManager.GetString("Reception_Model_GumColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string Reception_Model_Patient {
            get {
                return ResourceManager.GetString("Reception_Model_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion#.
        /// </summary>
        public static string Reception_Model_Reception {
            get {
                return ResourceManager.GetString("Reception_Model_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Reception_Model_State {
            get {
                return ResourceManager.GetString("Reception_Model_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Prueba.
        /// </summary>
        public static string Reception_Model_TestDate {
            get {
                return ResourceManager.GetString("Reception_Model_TestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Diente.
        /// </summary>
        public static string Reception_Model_ToothColor {
            get {
                return ResourceManager.GetString("Reception_Model_ToothColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Total.
        /// </summary>
        public static string Reception_Model_TotalValue {
            get {
                return ResourceManager.GetString("Reception_Model_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string Reception_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Reception_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asiganar Trabajos.
        /// </summary>
        public static string ReceptionAssign_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("ReceptionAssign_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string ReceptionWork_Model_Cantidad {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string ReceptionWork_Model_Precio {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string ReceptionWork_Model_Reception {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string ReceptionWork_Model_Tasa {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ReceptionWork_Model_Total {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        public static string ReceptionWork_Model_Work {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string ReceptionWork_Model_WorkCategory {
            get {
                return ResourceManager.GetString("ReceptionWork_Model_WorkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception Trabajo.
        /// </summary>
        public static string RecpetionWork_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("RecpetionWork_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string Register_Model_Bill {
            get {
                return ResourceManager.GetString("Register_Model_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string Register_Model_BillingNote {
            get {
                return ResourceManager.GetString("Register_Model_BillingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string Register_Model_Expenses {
            get {
                return ResourceManager.GetString("Register_Model_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Tecnicos.
        /// </summary>
        public static string Register_Model_PayTechnicians {
            get {
                return ResourceManager.GetString("Register_Model_PayTechnicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string Register_Model_Reception {
            get {
                return ResourceManager.GetString("Register_Model_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string Register_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Register_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string RepAssignDetail_Model_Cantidad {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Servicio.
        /// </summary>
        public static string RepAssignDetail_Model_CategoryService {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_CategoryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string RepAssignDetail_Model_NivelPrecio {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_NivelPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string RepAssignDetail_Model_Precio {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string RepAssignDetail_Model_Service {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnico.
        /// </summary>
        public static string RepAssignDetail_Model_Tecnico {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_Tecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string RepAssignDetail_Model_Total {
            get {
                return ResourceManager.GetString("RepAssignDetail_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignacion Tecnicos.
        /// </summary>
        public static string RepAssignDetail_ViewIndex_Titulo {
            get {
                return ResourceManager.GetString("RepAssignDetail_ViewIndex_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} es Requerido.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Sell_Model_Address {
            get {
                return ResourceManager.GetString("Sell_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string Sell_Model_Bill {
            get {
                return ResourceManager.GetString("Sell_Model_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string Sell_Model_BillingNote {
            get {
                return ResourceManager.GetString("Sell_Model_BillingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Sell_Model_Client {
            get {
                return ResourceManager.GetString("Sell_Model_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condicion.
        /// </summary>
        public static string Sell_Model_Condition {
            get {
                return ResourceManager.GetString("Sell_Model_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Sell_Model_Control {
            get {
                return ResourceManager.GetString("Sell_Model_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimiento.
        /// </summary>
        public static string Sell_Model_ExpirationDate {
            get {
                return ResourceManager.GetString("Sell_Model_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Sell_Model_Fecha {
            get {
                return ResourceManager.GetString("Sell_Model_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string Sell_Model_HeadText {
            get {
                return ResourceManager.GetString("Sell_Model_HeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Identidad.
        /// </summary>
        public static string Sell_Model_ID {
            get {
                return ResourceManager.GetString("Sell_Model_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Sell_Model_IDType {
            get {
                return ResourceManager.GetString("Sell_Model_IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Sell_Model_IVA {
            get {
                return ResourceManager.GetString("Sell_Model_IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Sell_Model_Phone {
            get {
                return ResourceManager.GetString("Sell_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string Sell_Model_Reception {
            get {
                return ResourceManager.GetString("Sell_Model_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string Sell_Model_SubTotal {
            get {
                return ResourceManager.GetString("Sell_Model_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Sell_Model_Total {
            get {
                return ResourceManager.GetString("Sell_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Sell_Model_Zona {
            get {
                return ResourceManager.GetString("Sell_Model_Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string Sell_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Sell_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string SellDetail_Model_Cantidad {
            get {
                return ResourceManager.GetString("SellDetail_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string SellDetail_Model_Codigo {
            get {
                return ResourceManager.GetString("SellDetail_Model_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string SellDetail_Model_Concepto {
            get {
                return ResourceManager.GetString("SellDetail_Model_Concepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string SellDetail_Model_Tasa {
            get {
                return ResourceManager.GetString("SellDetail_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string SellDetail_Model_Total {
            get {
                return ResourceManager.GetString("SellDetail_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unitario.
        /// </summary>
        public static string SellDetail_Model_Unitario {
            get {
                return ResourceManager.GetString("SellDetail_Model_Unitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string Service_Model_Service {
            get {
                return ResourceManager.GetString("Service_Model_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string Service_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Service_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string ServiceCategory_Model_Categoria {
            get {
                return ResourceManager.GetString("ServiceCategory_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Servicio.
        /// </summary>
        public static string ServiceCategory_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("ServiceCategory_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ServiceCateogry_Model_Detail {
            get {
                return ResourceManager.GetString("ServiceCateogry_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State_Model_Estado {
            get {
                return ResourceManager.GetString("State_Model_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibido.
        /// </summary>
        public static string State_Recibido {
            get {
                return ResourceManager.GetString("State_Recibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State_ViewIndex_Titulo {
            get {
                return ResourceManager.GetString("State_ViewIndex_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sistema/Texto Condiciones, puede ingresar el nuevo texto que desea ver en este espacio..
        /// </summary>
        public static string SupportText_Default {
            get {
                return ResourceManager.GetString("SupportText_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Condiciones.
        /// </summary>
        public static string SupportText_Model_TextoCondicion {
            get {
                return ResourceManager.GetString("SupportText_Model_TextoCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Condiciones.
        /// </summary>
        public static string SupportText_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("SupportText_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_Model_Impuesto {
            get {
                return ResourceManager.GetString("Tax_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL Valor del {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string Tax_Model_RangeMsg {
            get {
                return ResourceManager.GetString("Tax_Model_RangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string Tax_Model_Tasa {
            get {
                return ResourceManager.GetString("Tax_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Tax_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnico.
        /// </summary>
        public static string Techincal_Model_FullName {
            get {
                return ResourceManager.GetString("Techincal_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajos por Pagar.
        /// </summary>
        public static string TechincalPay_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("TechincalPay_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnico.
        /// </summary>
        public static string Technical_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Technical_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo Pago.
        /// </summary>
        public static string TechnicalPay_MetodoPago {
            get {
                return ResourceManager.GetString("TechnicalPay_MetodoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Pago.
        /// </summary>
        public static string TechnicalPay_Model_BillingNote {
            get {
                return ResourceManager.GetString("TechnicalPay_Model_BillingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturado.
        /// </summary>
        public static string TechnicalPay_Model_Facturado {
            get {
                return ResourceManager.GetString("TechnicalPay_Model_Facturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Tecnicos.
        /// </summary>
        public static string TechnicalPay_PagoTecnicos {
            get {
                return ResourceManager.GetString("TechnicalPay_PagoTecnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        public static string TechnicalWork_ButtonComment {
            get {
                return ResourceManager.GetString("TechnicalWork_ButtonComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo Tecnicos.
        /// </summary>
        public static string TechnicalWork_IndexTitulo1 {
            get {
                return ResourceManager.GetString("TechnicalWork_IndexTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepcion.
        /// </summary>
        public static string TechnicalWork_Model_Reception {
            get {
                return ResourceManager.GetString("TechnicalWork_Model_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string TecnichalPorcentage_Model_Company {
            get {
                return ResourceManager.GetString("TecnichalPorcentage_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string TecnichalPorcentage_Model_Porcentaje {
            get {
                return ResourceManager.GetString("TecnichalPorcentage_Model_Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro por Porcentaje.
        /// </summary>
        public static string TecnichalPorcentage_Titulo_Cobro_por_Porcentaje {
            get {
                return ResourceManager.GetString("TecnichalPorcentage_Titulo_Cobro por Porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sistema/Texto Encabezado, podra cambiar por la direccion, telefono y correo.
        /// </summary>
        public static string TextHead_Default {
            get {
                return ResourceManager.GetString("TextHead_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string TextHead_Model_TextEncabezado {
            get {
                return ResourceManager.GetString("TextHead_Model_TextEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string TextHead_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("TextHead_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ToothColor_Model_Detalle {
            get {
                return ResourceManager.GetString("ToothColor_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Diente.
        /// </summary>
        public static string ToothColor_Model_ToothColor {
            get {
                return ResourceManager.GetString("ToothColor_Model_ToothColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Diente.
        /// </summary>
        public static string ToothColor_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("ToothColor_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string User_Model_Address {
            get {
                return ResourceManager.GetString("User_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string User_Model_Company {
            get {
                return ResourceManager.GetString("User_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string User_Model_Email {
            get {
                return ResourceManager.GetString("User_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FisrtName {
            get {
                return ResourceManager.GetString("User_Model_FisrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FullName {
            get {
                return ResourceManager.GetString("User_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string User_Model_LastName {
            get {
                return ResourceManager.GetString("User_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string User_Model_Phone {
            get {
                return ResourceManager.GetString("User_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string User_Model_Photo {
            get {
                return ResourceManager.GetString("User_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string User_Model_Puesto {
            get {
                return ResourceManager.GetString("User_Model_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("User_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ViewCreate {
            get {
                return ResourceManager.GetString("ViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ViewDelete {
            get {
                return ResourceManager.GetString("ViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Work_Model_Category {
            get {
                return ResourceManager.GetString("Work_Model_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Work_Model_Detail {
            get {
                return ResourceManager.GetString("Work_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 1.
        /// </summary>
        public static string Work_Model_Price1 {
            get {
                return ResourceManager.GetString("Work_Model_Price1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 2.
        /// </summary>
        public static string Work_Model_Price2 {
            get {
                return ResourceManager.GetString("Work_Model_Price2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 3.
        /// </summary>
        public static string Work_Model_Price3 {
            get {
                return ResourceManager.GetString("Work_Model_Price3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Work_Model_Tax {
            get {
                return ResourceManager.GetString("Work_Model_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        public static string Work_Model_Work {
            get {
                return ResourceManager.GetString("Work_Model_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo.
        /// </summary>
        public static string Work_VIewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Work_VIewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string WorkCategory_Model_Categoria {
            get {
                return ResourceManager.GetString("WorkCategory_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Trabajos.
        /// </summary>
        public static string WorkCategory_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("WorkCategory_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string WorkCateogry_Model_Detail {
            get {
                return ResourceManager.GetString("WorkCateogry_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string WorkStation_Model_Detail {
            get {
                return ResourceManager.GetString("WorkStation_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion Trabjo.
        /// </summary>
        public static string WorkStation_Model_WorkStation {
            get {
                return ResourceManager.GetString("WorkStation_Model_WorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacion Trabajo.
        /// </summary>
        public static string WorkStation_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("WorkStation_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_Model_Zone {
            get {
                return ResourceManager.GetString("Zone_Model_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Zone_ViewIndex_Titulo1", resourceCulture);
            }
        }
    }
}
